steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t us-west1-docker.pkg.dev/microservices-445003/image-registry/orders-ms-prod -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-west1-docker.pkg.dev/microservices-445003/image-registry/orders-ms-prod',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/357122973934/secrets/orders_database_url
    env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY